repos:
  # 1. General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: requirements.txt
      - id: trailing-whitespace

  # 2. Formatting
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types: [python]
        pass_filenames: true

  # 3. Linting
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --fix --exit-non-zero-on-fix --show-fixes
        language: system
        types: [python]
        pass_filenames: true

  # 4. Tests
  - repo: local
    hooks:
      - id: pytest
        name: Run Integration Tests
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
