version: "3.7"

services:
  db:
    image: postgres:12.15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: fastapi_app_db
    command: -p 5434
    expose:
      - 5434
    env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db

volumes:
  postgres_data:
