version: "3.7"

services:
  redis:
    image: redis:7
    container_name: alola_api_redis_app

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: alola_api_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 4765:8000